Remove hard-coded setting of HTTP_PROXY in Umbrella
Replace the usage of urllib2 with wget to download

In case when HTTP_PROXY is set, urllib2 module of python fails when
urllib2.urlopen is called:
	AttributeError: 'module' object has no attribute 'URLerror'