Use itable to avoid compiler warning.
I don't see an easier way around this warning from gcc 4.9.0:

COMPILE pfs_main.o
pfs_main.cc: In function ‘void handle_event(pid_t, int, rusage*)’:
pfs_main.cc:356:47: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
       set_insert(stopped_threads, (void *) p->pid);
                                               ^
cc1plus: all warnings being treated as errors
../../Makefile.rules:9: recipe for target 'pfs_main.o' failed

Introduced in 97fb3f42713be6a5698b6e4d0ddcc5e700155dd9.